#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := project_template
CFLAGS += -DICACHE_FLASH

include $(IDF_PATH)/make/project.mk

